### ISSUE TITLE
No DATA in Zabbix

### ISSUE THREAD

**Issue by piboxx** [pschmitt/zabbix-template-speedtest#14]
Hello Philipp,

I don't know if your project is still being followed.

My problem is that I have no data in Zabbix and Grafana, the zbx-speedtest.sh script is ok manually - no error

I have debian10, zabbix 5.2.1, grafana 7.3.3
The template import is ok, I can see the metrics well but no data appears in Grafana.

I created a Dashboard in Zabbix but no data

I have been following your Debian installation and have not encountered any problems.

Can you help me try to see more clearly :-)

Thanks for your time and help.

Piboxx

**Comment by pschmitt** [comment]
Hi. Was it a config issue on your setup then?
