### ISSUE TITLE
Speedtest fails after a while. Removing /tmp/speedtest.json fixes it temporarily.

### ISSUE THREAD

**Issue by wojciehm** [pschmitt/zabbix-template-speedtest#15]
Every now and then speedtest stops to work.

In /tmp there are two files **speedtest.json** and **speedtest.json.new**. I have to manually remove the files and it start to works. 

What could be the cause?

**Comment by pschmitt** [comment]
> What could be the cause?

Hard to say without any logs.
My guess would be permissions :man_shrugging:

**Comment by backl1n** [comment]
@pschmitt @wojciehm have you found solution definitly ? for patch this problem i have identical problem ,

**Comment by wojciehm** [comment]
I haven't found the solution. Actually, right now when I type I have this issue. I just remove those files and it works.

**Comment by backl1n** [comment]
@wojciehm I will try to change the directory of the json for that comes from her I think

**Comment by backl1n** [comment]
it usually works 1 hour after it breaks @wojciehm I'll let you know if your discord we can watch my discord together 
@B4ckL1n#8384

**Comment by backl1n** [comment]
- @wojciehm I found a solution for our problem you create cron and you execute the script every ours and its fixing 
- 
![image](https://user-images.githubusercontent.com/40395422/189188350-a29ff771-c830-4261-b291-ce8ac893870e.png)

**Comment by wojciehm** [comment]
@backl1n will try that

@pschmitt 

This is today's execution. A lot of not executed ones. What s this MAX_AGE setting? How does this affect script?
I know we can change values but I am not sure what it does.


![image](https://user-images.githubusercontent.com/19718255/189192960-9ff2ca58-c03f-4714-b7ef-8219f8be048d.png)

**Comment by backl1n** [comment]
@wojciehm can you show error in zabbix web interface in key 
![image](https://user-images.githubusercontent.com/40395422/189193407-3470551b-35fa-4b07-b783-db233f394597.png)
here show me error

**Comment by pschmitt** [comment]
Yeah so it seems that you guys didn't install and/or enable the systemd timer/cronjob.

See the README and the systemd/ dir.
