### ISSUE TITLE
zbx-speedtest.sh[9436]: usage: speedtest Errors

### ISSUE THREAD

**Issue by lslamp** [pschmitt/zabbix-template-speedtest#16]
This was all working without any issues and then it broke. I have tried removing it completely from zabbix and reinstalling it. All without success.

I have some issues with permissions and then found the info about manually deleting the speedtest.json and speedtest.json.new. After manually removing these files from the /tmp/ dir, the error changed. Below is what I am seeing in the syslog file.

Dec 22 14:25:03 kodi systemd[1]: Started Run a speedtest.
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]: usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]:                  [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]:                  [--csv-header] [--json] [--list] [--server SERVER]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]:                  [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]:                  [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]:                  [--version]
Dec 22 14:25:03 kodi zbx-speedtest.sh[9730]: speedtest: error: unrecognized arguments: --accept-license --accept-gdpr -f json
Dec 22 14:25:03 kodi systemd[1]: zabbix-speedtest.service: Succeeded.

FYI: I am running this all on Ubuntu 20.04. I am currently using the debian version of the script. zbx-speedtest-debian.sh

After the test has run, I am seeing no data in the graph.
Any ideas why this is happening.
Thanks
Lawrence

**Comment by pschmitt** [comment]
Judging from the logs you didn't install the right Speedtest cli tool. I probably should add a big ass warning to the readme.

The one you need is the one by ookla:

https://www.speedtest.net/apps/cli

**Comment by lslamp** [comment]
I have speedtest-cli installed and as said on the URL provided that was the incorrect version. After removal and installing the plain speedtest all worked and now I have data on my dashboard.

Thanks for the great help and app.

Lawrence
