### ISSUE TITLE
Adding speed.latency to template

### ISSUE THREAD

**Issue by lslamp** [pschmitt/zabbix-template-speedtest#17]
Philip,

This is not an issue, but an addition request.
Again thank you very much for a very good template for zabbix. It helps me very much indeed.
I was looking at the template and you have 6 items under the template, Download, Upload, Jitter, Ping, Server and Timestamp. I would like to add Latency to this list.
I have looked at the json output and latency does exist, next to jitter. So I tried to clone jitter and just replace the work jitter with latency, but this did not work.
I tried adding the item to the zabbix server, but this showed as "not supported"
![latencyitem](https://user-images.githubusercontent.com/6013759/102989198-800e9080-4515-11eb-881d-492d2bd98757.png)
I tried to figure out where and how the template was extracting the delivered entities but could not, so would very much appreciate your guidance with adding latency to this template.

Thanks
Lawrence

**Comment by pschmitt** [comment]
Heyhey,

to add a new metric you need to alter the [agent config](https://github.com/pschmitt/zabbix-template-speedtest/blob/master/zabbix_agentd.d/speedtest.conf). In your case that would be something like the following:

```
UserParameter=speedtest.latency,/etc/zabbix/bin/zbx-speedtest.sh -l
```

... which in itself will not make this immediately work. You'd still need to edit the [script](https://github.com/pschmitt/zabbix-template-speedtest/blob/master/zbx-speedtest.sh) accordingly (ie. to accept the `-l` flag and return the latency in this case).

Mind opening a PR for this then, once you get it working?

**Comment by lslamp** [comment]
Philip, what is a PR, sorry, I am very new to this. I will be very happy to create it.

Oh yes I did get it working first time. I managed to figure out additions to the script and all worked. The only issue I had was that the measurement is set in ms and I am pretty sure that is way too fine. I will try to change it to seconds.

Yet again, great support and great advice.
Incredible.
Thanks
Lawrence

**Comment by lslamp** [comment]
Philip,

I am very sure I have done this incorrectly, but hope to do it better next time if that ever happens.
Please clarify.
I should have created a branch first, edited the necessary files in the branch, and then from the branch create a pull request.

I did it the other way round. Sorry for the confusion.
Lawrence

**Comment by pschmitt** [comment]
Let's continue this in #18 since you figured out on your own how to create a PR and all :+1: 
99% of the work is done now, thanks!

**Comment by lslamp** [comment]
Philip,
I have stumbled across something a little strange.
Looking at the json file created with each test. Look at the values delivered for ping.jitter and ping.latency I assume that these values are delivered in seconds. If this is the case, then the graph will not show the data correctly.The jitter graph is good, but it is the latency graph that is very strange. See screenshot below.
![item_unit](https://user-images.githubusercontent.com/6013759/103106378-564c8b00-4635-11eb-906f-4da3be90249a.png)
The jitter shows in milliseconds and the range is between 0 and 200 ms.
the latency shows in milliseconds as well, but the range is very big.
If I edit the item and change the unit from ms to s, then the latency value changes to years and days. See below.
![item_latency_unit](https://user-images.githubusercontent.com/6013759/103106506-716bca80-4636-11eb-9a1b-8352485b2664.png)
No matter what I try, mins or hours the units don't show with a good value. 
"ping":{"jitter":0.071999999999999995,"latency":2.3889999999999998}

Do you have any idea how we can show the latency data in seconds and be of a range between 0 and say 5 seconds or something?

Thanks
Lawrence

**Comment by lslamp** [comment]
Philip,
Don't hassle. I figured out what the issue was. I have placed a typo in the edit in the zbx-speedtest.sh script.

After fixing the typo and clearing the data I now have good results.
I have updated the fix in my branch.
Lawrence

**Comment by lslamp** [comment]
Philip,

Oops, seems that what I did, did not fix the issue.
What I had that delivered data, but I am not sure why, and also it delivered the strange times intervals shown above.
get_last_latency_time() {
  jq -r '.latency' "$DATA_FILE"

I then went and added .ping before .latemcy as shown below

get_last_latency_time() {
  jq -r '**.ping**.latency' "$DATA_FILE"

After this additiion of the .ping, no data was delivered in the graph but the times shown were good.

![ping_latency_nodata](https://user-images.githubusercontent.com/6013759/103111407-fc57bf80-464c-11eb-8bee-5f325e6ad641.png)

It seems that there are two entries in the file now with the same values.
The one in ping_time and the second is ping_latency How can I differentiate between them. The one I am looking for the ping turnaround and the second is the latency time 

get_last_ping_time() {
  jq -r '.ping.latency' "$DATA_FILE"
}

get_last_latency_time() {
  jq -r '.ping.latency' "$DATA_FILE"

Please clarify?
Thanks
Lawrence

**Comment by lslamp** [comment]
Philip,
Did some reading and it seems that the important measurement is the latency and not the ping. Ping is in one direction and latency is the turn-around time.
So please ignore.
Lawrence

**Comment by pschmitt** [comment]
So, now that I have actually looked into this I must close this issue since the requested metric is already available under `Speedtest - PING`.

**Comment by pschmitt** [comment]
https://github.com/pschmitt/zabbix-template-speedtest/blob/6186528005bedad57e5fdf14655e1e512a5085e6/zbx-speedtest.sh#L29-L31

**Comment by pschmitt** [comment]
:arrow_right: `zbx-speedtest.sh -p`
