### ISSUE TITLE
[[: not found

### ISSUE THREAD

**Issue by onurzaim** [pschmitt/zabbix-template-speedtest#19]
On debian 10 I hed these issues

/etc/zabbix/bin/zbx-speedtest.sh: 135: /etc/zabbix/bin/zbx-speedtest.sh: [[: not found
/etc/zabbix/bin/zbx-speedtest.sh: 137: /etc/zabbix/bin/zbx-speedtest.sh: [[: not found
/etc/zabbix/bin/zbx-speedtest.sh: 61: /etc/zabbix/bin/zbx-speedtest.sh: [[: not found

I could fix them by changing like this 

61:  [ "$(( now - data_ts ))" -gt "$MAX_AGE" ]
135: if [ "$ACTION" \!= "run" ]
137: if [ "$MAX_AGE" -gt 0 ] && data_is_outdated

**Comment by pschmitt** [comment]
How did you run it *exactly*? The shebang clearly states bash.

**Comment by onurzaim** [comment]
I copied as you suggested from your directions.

**Comment by pschmitt** [comment]
Where did you get the above error message from then?

**Comment by onurzaim** [comment]
I got it directly in zabbix and in bash when I run manually.

**Comment by pschmitt** [comment]
**Akinator mode activated**.

Here's my final guess: you are executing the wrong file. Please refer to the Debian specific instructions in the README :point_down: 

> Copy zbx-speedtest-debian.sh to /etc/zabbix/bin/zbx-speedtest.sh
