### ISSUE TITLE
Server_ID Not found

### ISSUE THREAD

**Issue by sloucks** [pschmitt/zabbix-template-speedtest#4]
Getting the following issue when the script runs: 
/etc/zabbix/script/speedtest.sh: 9: /etc/zabbix/script/speedtest.sh: SERVER_ID[0]=3997: not found

It doesn't matter what the server ID is set to.

**Comment by doumhfr** [comment]
I have exactly the same error. do you have find a solution?

**Comment by tsedgwick1** [comment]
Did you find a solution to the issue ?

**Comment by pschmitt** [comment]
What hardware are you guys on?

**Comment by thiagocrepaldi** [comment]
change the first line of speedtest.sh from `#!/usr/bin/env sh` to `#!/bin/bash`

`SERVER_ID[0]` is a bash construction whereas `/usr/bun/env sh` is pointing to `dash`
