### ISSUE TITLE
Issues on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by leonroy** [pschmitt/zabbix-template-speedtest#6]
Firstly noticed the file *zbx-speedtest.sh* used to have `#!/usr/bin/env bash` as per:
https://github.com/pschmitt/zabbix-template-speedtest/issues/2

But this change reverted when the sh script was updated.

Also in *zabbix-speedtest.service* `User` is `zabbix-agent`. On Ubuntu the default Zabbix user is just `zabbix` so might want to mention in the *README.md* the need to change this value to the right user on Ubuntu systems.

Thanks for the great work, all working here with those changes.

**Comment by pschmitt** [comment]
hm, I actually changed that so that the script works on OpenWRT, which does not ship with bash, but ash. I'm afraid there's no easy fits-all solution for this.

![image](https://user-images.githubusercontent.com/37886/80312584-2dde6980-87e6-11ea-8f64-77c087a2fa98.png)
